spring.datasource:
  url: jdbc:postgresql://localhost:5432/trus_test
  username: postgres
  password: Heslo12!
  driver-class-name: org.postgresql.Driver

spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

server:
  ssl:
    key-store: file:C:\Users\matej\Desktop\trusi_appka\server\trus\springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8443

spring-doc:
  api-docs.path: /api-docs

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  jackson:
    mapper:
      accept-case-insensitive-enums: true
