spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.jpa.defer-datasource-initialization: true


server:
  port: 8080

springdoc:
  api-docs.path: /api-docs

spring:
  profiles:
    active: prod
  sql:
    init:
      mode: always
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  jackson:
    mapper:
      accept-case-insensitive-enums: true
notifications:
  enabled: ${NOTIFICATIONS_ENABLED:true}
