package com.jumbo.trus.entity.outbox;

public enum OutboxEventType {

    MATCH_CREATED,
    MATCH_UPDATED,
    MATCH_DELETED,

    MATCH_PLAYERS_CHANGED,
    MATCH_WEATHER_CHANGED,

    BEER_CHANGED,
    RECEIVED_FINE_CHANGED,
    GOAL_CHANGED,

    PLAYER_CREATED,
    PLAYER_UPDATED,
    PLAYER_DELETED,

    SEASON_CREATED,
    SEASON_UPDATED,
    SEASON_DELETED,

    FINE_CREATED,
    FINE_UPDATED,
    FINE_DELETED,

    FOOTBAR_SESSION_SAVED,
    FOOTBALL_MATCH_UPDATED,

    STEP_SYNCED
}
